### ISSUE TITLE
`3` `s`  `e` `g` `j` `M` `G` `J` `£` `¢` ROND outline issues

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#428]
- [ ]  `3`
<img width="462" alt="Screenshot 2023-02-27 at 2 12 03 PM" src="https://user-images.githubusercontent.com/22956348/221561615-6adacf05-e63c-4cf9-b44a-138da531ef52.png">

- [ ]   `s`

<img width="500" alt="Screenshot 2023-02-27 at 2 23 29 PM" src="https://user-images.githubusercontent.com/22956348/221563072-d631d069-b02e-4042-a991-02859217d380.png">

- [x] `e` `g` 

<img width="513" alt="Screenshot 2023-02-27 at 2 20 29 PM" src="https://user-images.githubusercontent.com/22956348/221562404-1449fcdc-dc6e-44bd-8b0e-3f43bb783c40.png">

- [ ]  `j`

<img width="464" alt="Screenshot 2023-02-27 at 2 21 13 PM" src="https://user-images.githubusercontent.com/22956348/221562539-2924349e-002e-4226-ab31-113e25504878.png">

<img width="500" alt="Screenshot 2023-02-27 at 7 06 44 PM" src="https://user-images.githubusercontent.com/22956348/221649386-874e49d2-4a9a-46f8-8dff-ae7542f41def.png">

- [x] `M` 

<img width="708" alt="Screenshot 2023-02-27 at 2 19 10 PM" src="https://user-images.githubusercontent.com/22956348/221562128-f470bf83-f29f-4d0f-87bb-b6e12f7673b9.png">

- [x]  `G` `J`

<img width="605" alt="Screenshot 2023-02-27 at 2 19 46 PM" src="https://user-images.githubusercontent.com/22956348/221562244-134e8287-3431-4f93-aca1-a39079490321.png">

- [x] `£`
<img width="460" alt="Screenshot 2023-02-27 at 7 57 02 PM" src="https://user-images.githubusercontent.com/22956348/221645115-77a3d9c4-e703-495d-a372-6b4f5c35ab1c.png">

- [x]   `¢`
<img width="464" alt="Screenshot 2023-02-27 at 7 58 55 PM" src="https://user-images.githubusercontent.com/22956348/221645345-5d208144-9def-4af5-81c6-9d15a09db6be.png">

- [x] `µ` 
<img width="652" alt="Screenshot 2023-02-27 at 8 15 26 PM" src="https://user-images.githubusercontent.com/22956348/221648996-610cda13-5724-4529-acd3-cba98d857f89.png">

- [x] `§`

<img width="522" alt="Screenshot 2023-02-27 at 8 03 57 PM" src="https://user-images.githubusercontent.com/22956348/221649058-0c623821-a8fe-4e60-bf8c-09207c078f37.png">

- [x] `¨`

<img width="498" alt="Screenshot 2023-02-27 at 8 03 00 PM" src="https://user-images.githubusercontent.com/22956348/221649035-ee4346ee-3759-4491-a016-ddfa7c2fc3a8.png">

- [x] `&`
<img width="533" alt="Screenshot 2023-02-27 at 3 06 05 PM" src="https://user-images.githubusercontent.com/22956348/221649600-16a6664e-edf0-43ae-8bce-58ef5ed33502.png">

- [ ]  `ß`
<img width="583" alt="Screenshot 2023-02-27 at 8 27 13 PM" src="https://user-images.githubusercontent.com/22956348/221651298-d9e5eafc-7baf-46aa-a417-c30c395e06ad.png">

- [x]   `Ħ`
<img width="807" alt="Screenshot 2023-02-27 at 8 33 58 PM" src="https://user-images.githubusercontent.com/22956348/221652476-214addf5-f854-4f08-a225-f40b29dfd6ba.png">

**Comment by MariannaPaszkowska** [comment]
@sannorozco I finished the review for today. I reviewed the interpolation of most of the base glyphs. Issues are posted on the repository.

CC @dberlow @chrissimpkins @davelab6

**Comment by chrissimpkins** [comment]
@dberlow @sannorozco Status?

**Comment by sannorozco** [comment]
@chrissimpkins All glyphs have been fixed, remaining is the '&' which is in progress.

**Comment by MariannaPaszkowska** [comment]
@sannorozco Issues still persist in [the latest sources](https://github.com/googlefonts/googlesans-flex/actions/runs/4303113101): 
cc @chrissimpkins 


- [ ] `3`
<img width="634" alt="Screenshot 2023-03-01 at 6 36 27 PM" src="https://user-images.githubusercontent.com/22956348/222203673-cc816c63-92a9-4f8c-9da7-52afc8d7fb75.png">


- [ ] `s`
<img width="578" alt="Screenshot 2023-03-01 at 3 57 17 PM" src="https://user-images.githubusercontent.com/22956348/222161289-3538556b-4d3a-4a74-ab9e-1ed280f8f5ff.png">


- [ ] `j`
<img width="542" alt="Screenshot 2023-03-01 at 3 58 41 PM" src="https://user-images.githubusercontent.com/22956348/222161724-f8e7e8aa-bac7-4716-8152-d073a55fa5b7.png">
<img width="521" alt="Screenshot 2023-03-01 at 3 58 37 PM" src="https://user-images.githubusercontent.com/22956348/222161742-52133e2c-a9e5-4f70-9164-54c6cb234f22.png">

- [ ] `ß`
<img width="422" alt="Screenshot 2023-03-01 at 4 00 29 PM" src="https://user-images.githubusercontent.com/22956348/222162176-f45ea4ee-7b38-47c7-9fb3-c644ebcb080c.png">

<img width="657" alt="Screenshot 2023-03-01 at 6 23 36 PM" src="https://user-images.githubusercontent.com/22956348/222200216-bda5246e-2907-4a58-afd1-16c8bad59fd9.png">

**Comment by MariannaPaszkowska** [comment]
<img width="688" alt="Screenshot 2023-03-01 at 6 46 48 PM" src="https://user-images.githubusercontent.com/22956348/222206264-fdcd68ca-7fad-439f-834c-5ad71189cb60.png">

**Comment by MariannaPaszkowska** [comment]
<img width="727" alt="Screenshot 2023-03-01 at 6 47 48 PM" src="https://user-images.githubusercontent.com/22956348/222206476-96fe08bc-530c-4a73-80a6-5da7748b81cf.png">

**Comment by MariannaPaszkowska** [comment]
<img width="713" alt="Screenshot 2023-03-01 at 6 48 16 PM" src="https://user-images.githubusercontent.com/22956348/222206647-71db53ed-d608-42f6-beda-dcbbca758b8e.png">

**Comment by MariannaPaszkowska** [comment]
- [ ] S 
<img width="693" alt="Screenshot 2023-03-01 at 6 48 49 PM" src="https://user-images.githubusercontent.com/22956348/222206753-e11e23d7-f7a7-42d4-adbb-79a07fe07867.png">
